### ISSUE TITLE
Open the list as soon as you enter the edit mode

### ISSUE THREAD

**Issue by MartinFreire** [avallete/ag-grid-autocomplete-editor#23]
Hi, there is way to open the list as soon as you enter the edit mode?

In some cases the user doesn't know the possible values, and if the values list is not huge, I think it's better to show the full list so it can see all the options he can choose.

There's some way to accomplish this?

Note: I research the autocomplete library but it seems that it will require a fix with yours
https://github.com/kraaden/autocomplete/issues/20

Thanks for all!

**Comment by avallete** [comment]
Hi,

It seem like a good feature to me.

Thank's to your link, I find the commit implementing this behavior on autocomplete library: https://github.com/kraaden/autocomplete/commit/15462617aa41959294586a54fae6d8693530578d

It doesn't look too complicated too me, it will probably only require to change the `autocomplete/autocomplete.ts` file.

I will try to do it this weekend when I have some time.

**Comment by avallete** [comment]
Well, don't need to wait the end of the week since I managed to free some time today I've implemented this new option.

It's available on package v1.2.0

Here a [minimal code example](https://stackblitz.com/edit/ag-grid-autocomplete-editor-showonfocus) showing how to use it with both, local data and server fetched data.

**Comment by MartinFreire** [comment]
Wooow, that's awesome! It works like a charm. Thanks!
