### ISSUE TITLE
Cannot read property 'suppressKeyboardEvent' of undefined

### ISSUE THREAD

**Issue by hbthanki** [avallete/ag-grid-autocomplete-editor#29]
https://github.com/avallete/ag-grid-autocomplete-editor/blob/84b9ff820e6550ecb34d0c2e4cb519340eda1727/ag-grid-autocomplete-editor.ts#L214

While debugging the code of editor, I have found that colDef not available in IAutocompleteSelectCellEditorParams (ICellEditorParams)

I am trying to use it with Angular 5.x and my ag-grid version is 17.

**Comment by avallete** [comment]
I think the issue come from your version of ag-grid, I doesn't encounter this issue in version >20.

Maybe you could fork the repo and try to find on your version of ag-grid who the cellEditor can access the colDef values or upgrade your version of ag-grid to the latest.

Since I have no intent to maintain old versions of ag-grid prior v20, I close this issue.
