### ISSUE TITLE
regenerate full list when previously entered data is deleted

### ISSUE THREAD

**Issue by bgovi** [avallete/ag-grid-autocomplete-editor#32]
The feature open the list as soon as you enter the edit mode is really nice. It makes sense to me that with this feature if i edit a cell that already has data and I delete all the contents in that cell the autocomplete list should render full original list. However it will show nothing until the first character is entered.

**Comment by avallete** [comment]
Hum, interesting, it would make sense.

This was an 'optimisation' I think to avoid the call to 'fetch' when no characters was typed. I will l try to fix this ASAP.

**Comment by avallete** [comment]
Post mortem:

The issue was happening because of conditional checks on `minLength` option parameter, which, when his value was set to `0` (to display the list even without letter in the input field) was detected as 'non set' and automatically set to `1` by default.

It has been fixed, you should now be able to get the behavior you want using `minLength: 0` parameter.

**Comment by bgovi** [comment]
I tried using the option. It did not seem to work. 

Below is what/where it was added. 

autocomplete:{
minLength: 0
}

**Comment by avallete** [comment]
Yep, my bad, I was unclear, this is probably because if you want the list to show up on focus, you have to use the `minLength` with the `showOnFocus` option because without this option it will not trigger the list displaying before the first entry (but will re-trigger it with no data if you enter something then delete it entirely).

Not sure I make myself very clear here, this is a full example showing the two behavior: https://stackblitz.com/edit/ag-grid-autocomplete-editor-showonfocus-8jx3zw

Hope it will help you.

**Comment by ying-zhou-git** [comment]
Hi, the same error was re-introduced [here](https://github.com/avallete/ag-grid-autocomplete-editor/blob/14a7ff5ddbfa4a11cf3cee69d4e10a16b980c731/autocompleter/autocomplete.ts#L64)
