### ISSUE TITLE
How can I use it with TypeScript

### ISSUE THREAD

**Issue by jasp402** [avallete/ag-grid-autocomplete-editor#59]
How can I use it with TypeScript and reactjs
When I install it, it still doesn't recognize it.

![image](https://user-images.githubusercontent.com/8978470/78938230-78868480-7a77-11ea-944d-c3634feb2036.png)

It is usually solved using:
```
npm i @types/ag-grid-autocomplete-editor -S
```

**Comment by avallete** [comment]
Hi there,

I've just tested it here: https://stackblitz.com/edit/typescript-uqpiu9

And haven't been able to reproduce your issue. I do ship the type definition file (.d.ts) with the package so it should work with typescript. Maybe an issue with your code editor with caching/indexing of the nodes_modules ?

Also, maybe shipping the `.d.ts` within the module isn't the smartest option (since if you don't use TypeScript you don't need it and it take space into the package). I will read some advise about that and keep this issue open to maybe refactor the way we include the types to the package.
