### ISSUE TITLE
is it possible to access data from other columns from autocomplete?

### ISSUE THREAD

**Issue by SoyDiego** [avallete/ag-grid-autocomplete-editor#84]
Hi, I have two columns in my aggrid.
One with the autocomplete and other column (hidden) with ID.
I need get data from the column "ID" to call the API in my autocomplete and show the data right there.

![imagen](https://user-images.githubusercontent.com/19764334/96967889-6dc1a780-1510-11eb-886f-86693814d705.png)

Thanks

**Comment by avallete** [comment]
Yes, but it have nothing to do with the cellEditor itself. You need to create a scope where this data retrieved, you will be able to pass this data into the `fetch` function scope.

You probably want to check an [Grid Api](https://www.ag-grid.com/javascript-grid/grid-api/) and [Editing Api](https://www.ag-grid.com/javascript-grid/cell-editing/#editing-api) documentation.

I close this issue since it's not related to the plugin itself.
