### ISSUE TITLE
[BUG] Cannot read property PopupComponent

### ISSUE THREAD

**Issue by eyallibarak** [avallete/ag-grid-autocomplete-editor#96]
1. I'm loading ag-grid-autocomplete-editor with document.createElement('script') (src= .....ag-grid-autocomplete-editor.js) instead of "import {AutocompleteSelectCellEditor} from 'ag-grid-autocomplete-editor';"
2. I use the enterprise version of ag-grid (and have edited require("ag-grid-community") to require("ag-grid-enterprise"))
3. I get this error in the javascript console:

Uncaught TypeError: Cannot read property 'PopupComponent' of undefined
    at Object.220 (ag-grid-autocomplete-editor.js:1)

**Comment by avallete** [comment]
Probably a regression due to recent dependencies changes into https://github.com/avallete/ag-grid-autocomplete-editor/releases/tag/v2.2.1

Could you try with `ag-grid-autocomplete-editor@2.2.0` and tell me if the error still occurs ?

I try to reproduce and fix it ASAP.

**Comment by eyallibarak** [comment]
How does the require("@ag-grid-community/core") work?
With version 2.2.0 I still get the same error.
I attach ag-grid with simple script src=".." tag.

**Comment by avallete** [comment]
Basically, `require` go search in the `window` object the required dependency.

I relate your issue to the way `agGrid` is imported into your code. Because of the way you importing it (trough direct `src=""` tag). The module resolution have a hard time to resolve the `ag-grid-community` dependency.

However, you can "patch" this issue by aliasing the `window.agGrid` to the name wanted by the plugin (for latest version is `ag-grid-community`). I have created a gist to give you an exemple [here](https://gist.github.com/avallete/9b12f851374d838b480df32fbe903097). Please note that the order of the `<script>` tags into the HTML are important and cannot be reversed with one another.

Let me stress this: **I do not recommend this method**, instead, use `npm` + some bundling tools to handle your project dependencies and modules resolution. You can find some [docs on the official website](https://www.ag-grid.com/javascript-grid/packages/). That comes with several advantages (typescript types if you use it, .map.js for debugging). And will also give you some more comprehensive error messages at building time if something goes wrong.

Also, be aware that I'm working on a big refactor of the code in this module right now, and I will revert the `ag-grid-community` dependency to `@ag-grid-community/core` (so you will need to adapt the alias to reflect this change if when you pull the next update)

**Comment by eyallibarak** [comment]
I've tried adding this code after ag-grid script is loaded and before autocomplete-editor script is loaded.
window['ag-grid-community'] = window.agGrid;        
window['ag-grid-community/core'] = window.agGrid;
Not working still.

Btw, in agGrid tutorial I see they do recommend loading the script in a normal script src: 
[https://www.ag-grid.com/javascript-grid/getting-started/](https://www.ag-grid.com/javascript-grid/getting-started/)

**Comment by eyallibarak** [comment]
@avallete Thanks, I got it to work following your example.
